# Generated by Django 3.2.5 on 2021-07-21 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210720_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='super_rubric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.superrubric', verbose_name='Надрубрика'),
        ),
    ]
